# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'qimingliu'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Hometown', url: 'hometown'}
- {name: 'Technology', url: 'technology'}
- {name: 'Sports', url: 'sports'}
- {name: 'Music', url: 'music'}
- {name: 'Movies&Books', url: 'reading'}
- {name: 'Contact', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/GavinLi48240228'}
- {icon: 'facebook', link:   'https://www.facebook.com/liu.qiming.96/'}
- {icon: 'instagram', link:  'https://www.instagram.com/qimimg_liiiu/'}
- {icon: 'envelope', link:   'ql2298@nyu.edu'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
